inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'Guardfile'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
