name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails:
          - '6.1'
          - '6.0'
          - '5.2'
        ruby:
          - head
          - '3.0'
          - '2.7'
          - '2.6'
    continue-on-error: ${{ matrix.ruby == 'head' }}
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile.actionpack${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake
